
stages:
  - build
  - test

build-image:
    tags :
    - runner-shell-docker
    stage: build
    before_script:
      - echo "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
      - docker login -u "$CI_REGISTRY_USER"  -p "$CI_REGISTRY_PASSWORD"
    script:
      - |
        if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
          tag=""
          echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
        else
          tag=":$CI_COMMIT_BRANCH"
          echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
        fi
      - cd build
      - docker build --pull -t "$CI_REGISTRY_USER"/"${CI_PROJECT_NAME}:ci" -t "$CI_REGISTRY_USER"/"$CI_PROJECT_NAME${tag}" .
      - docker push "$CI_REGISTRY_USER"/"${CI_PROJECT_NAME}:ci"
      - docker push "$CI_REGISTRY_USER"/"$CI_PROJECT_NAME${tag}"
    rules:
      - if: $CI_COMMIT_BRANCH
        exists:
          - build/dockerfile

image:
  name: asofainy/calibre-web:ci
  pull_policy: always

A_Implementer:
  stage: test
  tags :
    - runner-kubernetes
  script:
     - /opt/toolbox/scripts/entrypoint.sh &
     - sleep 5 && exit 0